version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181
    networks:
      - mynetwork

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - mynetwork

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    environment:
      - KAFKA_HOST=172.18.0.2:9092 # Use the IP address of the Kafka container
      - KAFKA_TOPIC=book_shop_topic
    volumes:
      - ./app:/app
    networks:
      - mynetwork

networks:
  mynetwork:
